### ISSUE TITLE
[BUG] Mouse Jitter / General smoothness

### ISSUE THREAD

**Issue by rowbawts** [hmlendea/geforcenow-electron#101]
### Describe the bug

I'm using the Flatpak version and I've noticed that when I'm moving my mouse around there is a slight hitch/jitter to it and it's not smooth the same occurs when using the Chrome browser version, but the Windows desktop app performs so much better it feels like it's running locally. Is there any troubleshooting I can do to see if I can fix the issue I'm having to get closer to that or is that just inherent to this Electron app?

### To Reproduce

1. Install Flatpak version.
2. Launch a game. (BF4 used for testing between Windows 11 and Fedora)
3. Move mouse.

### Operatingsystem

Fedora 35 Silverblue

### Desktop Environment

GNOME 41.3

### Installation method

Flatpak

### Version

1.1.12

**Comment by hmlendea** [comment]
Feels like this is simply an electron limitation. The official Windows client performs better most of the time.

If you want you can try the following:
 - Making sure mouse smoothing / acceleration is disabled on your system
 - Trying a non-flatpak version to see if the issue is flatpak-related. The easiest to try would be the generic version by downloading the [zip from GitHub](https://github.com/hmlendea/geforcenow-electron/releases/latest), or the AppImage version; since neither requires installation.

**Comment by rowbawts** [comment]
I actually switched to Parsec with a cloud PC instead of trying to work this issue as I believe you are right the experience on Linux is just sub par due to the technical limitations of the browser client that us Linux users are limited to. Thanks for the project and the response as it is useful and does work you can only work with what they give us.
