### ISSUE TITLE
Mouse pointer resets to center of screen when moved too quickly

### ISSUE THREAD

**Issue by psy-q** [hmlendea/geforcenow-electron#2]
Once a game starts, I can only move the pointer reliably if I move it very, very slowly. Otherwise it resets to some center coordinates over and over.

Controller input works, though.

This is with Node 14.7.0 on openSUSE Tumbleweed, Plasma on X11.

**Comment by ntropy83** [comment]
Same here, also on Plasma 5 X11, Manjaro KDE

**Comment by DylanRob** [comment]
+1 also happens here, POP os 20.04

**Comment by hmlendea** [comment]
I'm currently investigating this but so far I got no solution

**Comment by DylanRob** [comment]
i will see what i can do in my spare time, and hopefully we can this!

**Comment by ntropy83** [comment]
I played a bit with mouse settings adaptive/flat but no chance. Happens in fullscreen and in the minimized window. Since its affecting the game popup window, there either a value has to be passed or its a GFN thing. 

I wasnt able so far to open the game from the browser alone, not with Chrome UA Spoofer.

**Comment by hmlendea** [comment]
> I played a bit with mouse settings adaptive/flat but no chance. Happens in fullscreen and in the minimized window. Since its affecting the game popup window, there either a value has to be passed or its a GFN thing.
> 
> I wasnt able so far to open the game from the browser alone, not with Chrome UA Spoofer.

In the browser if you get the "Unsupported platform" message (might be worded differently) even though you're sure you're setting the correct UA, then clear the cookies/cache for that page and try again. It worked for me that way.
And the mouse works fine in the browser, it's just here in Electron that it causes problems.

**Comment by hmlendea** [comment]
An interesting thing that I found is that if I open the devtools programatically in the streaming window, even when I alt tab (so that I get my system cursor back) and try to click anywhere on the dev tools, it just passes through to the stream and I can even hear the Windows error/warning sound.
So the GFN stream completely caputres the mouse as long as it is in the same screen area as its own.

**Comment by sigmaSd** [comment]
Hi, it works correctly with electron version 5 and 10

**Comment by hmlendea** [comment]
Hmmm can you elaborate a bit? Which versions exactly?
I have the issue on both `5.0.13` and `10.0.0-beta.23`

**Comment by hmlendea** [comment]
I've released v1.0.1 with this fix so that people can start using this app with their mouse not just their gamepads
However if some people are still affected by it, this issue can be reopened

**Comment by sigmaSd** [comment]
@hmlendea glad it helped!

**Comment by ntropy83** [comment]
Ok I tried deleting the cache for the UA spoofer but that did not work. Maybe it is because I use chromium and not chrome directly.

I tried the new program version and it crashed with a javascript error upon starting the stream. I uncommented this and now its running:

` main.js, line 40
     window.setPosition(
      mainWindowPosition[0] + (mainWindowSize[0] - windowSize[0]) / 2,
      mainWindowPosition[1] + (mainWindowSize[1] - windowSize[1]) / 2);`

Mouse is working now too, thank you. :+1:

**Comment by hmlendea** [comment]
@ntropy83  well this app uses Electron and Electorn uses Chromium so I'm not sure why it's not working. The GoL article however did say that it only works on Chrome.

Regarding the crash yes, I did experience it once also and I'll look into it tomorrow.
