### ISSUE TITLE
Can't do mouse or keyboard input, yellow border when i try to type or click.

### ISSUE THREAD

**Issue by databoose** [hmlendea/geforcenow-electron#20]
Title explains it all, here's a video demonstrating the issue : https://www.youtube.com/watch?v=6z_cyXWm6wQ

OS : Ubuntu 20.04.1 LTS
Kernel : 5.4.0-52-generic

**Comment by hmlendea** [comment]
I've also been having the border and I didn't find out exactly why it's happening.
I did however notice it's only happening when launching the Steam app itself. When launching a game directly, it works well.

It seems to be a GFN thing rather than being caused by this wrapper though.

In regards to not having input, I will look into it and investigate what's causing it as soon as I can. But right now I wasn't able to replicate the problem on my end.

PS: Usually I fix the border by shift+` to exit fullscreen and then going back into fullscreen. Does that work for you as well? Does it also solve the input by any chance?

**Comment by databoose** [comment]
> PS: Usually I fix the border by shift+` to exit fullscreen and then going back into fullscreen. Does that work for you as well? Does it also solve the input by any chance?

I just tested it and yes that does work, interesting.

I also forgot to mention i'm using ubuntu mate which is on top of ubuntu 20.04, perhaps it could be something to do with that but really i have no idea.

**Comment by databoose** [comment]
Also another issue i seem to have is that i cannot enter in the symbol "~" as it blocks the input and switches between fullscreen and windowed, unfortunately my password includes this symbol so i can't actually login to the steam client through GFN.

**Comment by hmlendea** [comment]
I don't have a solution yet, but I was able to reproduce the original issue on Ubuntu MATE using VirtualBox.

**Comment by seitbekir** [comment]
So after you've merged the PR preventing toggle of fullscreen there is no longer way to quit fullscreen or remove yellow border?

**Comment by nvaytet** [comment]
Also, could you explain how to launch a game directly?
