### ISSUE TITLE
Error on specific screen resolutions in arch based distros

### ISSUE THREAD

**Issue by Mekolaos** [hmlendea/geforcenow-electron#7]
Hi !

The issue is when launching a game and the desktop's resolution is at 1280*720 there's a weird javascript error coming up, and the game won't launch.

My friend has the same issue, except his screen can only go up to 720p.

There's part of a stack trace when the error dialog comes up, but no specific error.

Thanks for reading this.

**Comment by hmlendea** [comment]
Ah ok, I didn't expect anybody to run this at lower than 1366x768 which I thought would be as low as old laptops would go (mine included)
The default size that I've set for the main window is 1280x768 which is what I suspect would cause your crash, since it is larger than your screen's resolution.
I'll investigate it and if this is indeed the problem, then it would be an easy fix.

**Comment by hmlendea** [comment]
Could you upload the exact error that's displayed? A screenshot would suffice
